[build]
  builder = "nixpacks"

[deploy]
  startCommand = "bun src/index.ts"
  restartPolicyType = "ON_FAILURE" # Fix: Changed from "on-failure"
  restartPolicyMaxRetries = 3
  healthcheckPath = "/health"
  healthcheckTimeout = 300

[[services]]
  name = "domicop-api"
