// This file should be generated by running: supabase gen types typescript --project-id <project-id>
// For now, we define the core types manually based on the schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type ProfileStatus = 'pending' | 'active' | 'suspended'
export type ProfileRole = 'member' | 'admin'
export type ContributionStatus = 'pending' | 'verified' | 'rejected'
export type TransactionType = 'contribution' | 'loan_repayment' | 'levy' | 'dividend'
export type TransactionStatus = 'pending' | 'success' | 'failed' | 'reversed'
export type LoanType = 'emergency' | 'personal' | 'housing' | 'education' | 'business'
export type LoanStatus = 'pending' | 'under_review' | 'approved' | 'rejected' | 'disbursed' | 'repaying' | 'closed'
export type DividendStatus = 'pending' | 'processing' | 'success' | 'failed'
export type MessageStatus = 'open' | 'in_progress' | 'resolved' | 'closed'
export type NotificationType = 'payment' | 'loan' | 'announcement' | 'message' | 'general'
export type PaymentAttemptStatus = 'initiated' | 'success' | 'cancelled' | 'failed' | 'retry'

export interface Profile {
  id: string
  full_name: string
  phone: string | null
  address: string | null
  bank_name: string | null
  bank_account: string | null
  bank_code: string | null
  next_of_kin: string | null
  role: ProfileRole
  status: ProfileStatus
  onboarding_step: number
  onboarding_done: boolean
  fcm_token: string | null
  avatar_url: string | null
  member_no: string | null
  preferences: Json
  created_at: string
  updated_at: string
}

export interface Contribution {
  id: string
  member_id: string
  amount: number
  month: string
  year: number
  status: ContributionStatus
  proof_url: string | null
  payment_ref: string | null
  notes: string | null
  created_at: string
  updated_at: string
}

export interface Transaction {
  id: string
  member_id: string
  paystack_ref: string
  amount: number
  type: TransactionType
  status: TransactionStatus
  channel: string | null
  description: string | null
  contribution_id: string | null
  loan_id: string | null
  metadata: Json
  created_at: string
}

export interface Loan {
  id: string
  member_id: string
  amount_requested: number
  amount_approved: number | null
  purpose: string
  type: LoanType
  status: LoanStatus
  interest_rate: number
  tenure_months: number | null
  monthly_repayment: number | null
  balance: number
  disbursed_at: string | null
  due_date: string | null
  guarantor_id: string | null
  documents_url: string[] | null
  admin_notes: string | null
  created_at: string
  updated_at: string
}

export interface Dividend {
  id: string
  member_id: string
  amount: number
  year: number
  paystack_transfer_ref: string | null
  status: DividendStatus
  created_at: string
}

export interface Message {
  id: string
  member_id: string
  subject: string
  status: MessageStatus
  created_at: string
  updated_at: string
}

export interface MessageReply {
  id: string
  message_id: string
  sender_id: string
  body: string
  created_at: string
}

export interface Notification {
  id: string
  member_id: string
  title: string
  body: string
  type: NotificationType
  read: boolean
  data: Json
  created_at: string
}

export interface Announcement {
  id: string
  title: string
  body: string
  author_id: string | null
  published: boolean
  created_at: string
  updated_at: string
}

export interface AuditLog {
  id: string
  actor_id: string | null
  action: string
  entity: string
  entity_id: string | null
  metadata: Json
  created_at: string
}

export interface PaymentAttempt {
  id: string
  member_id: string
  paystack_ref: string
  status: PaymentAttemptStatus
  error_message: string | null
  metadata: Json
  created_at: string
}

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profile
        Insert: Omit<Profile, 'created_at' | 'updated_at'> & { created_at?: string; updated_at?: string }
        Update: Partial<Profile>
      }
      contributions: {
        Row: Contribution
        Insert: Omit<Contribution, 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }
        Update: Partial<Contribution>
      }
      transactions: {
        Row: Transaction
        Insert: Omit<Transaction, 'id' | 'created_at'> & { id?: string; created_at?: string }
        Update: Partial<Transaction>
      }
      loans: {
        Row: Loan
        Insert: Omit<Loan, 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }
        Update: Partial<Loan>
      }
      dividends: {
        Row: Dividend
        Insert: Omit<Dividend, 'id' | 'created_at'> & { id?: string; created_at?: string }
        Update: Partial<Dividend>
      }
      messages: {
        Row: Message
        Insert: Omit<Message, 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }
        Update: Partial<Message>
      }
      message_replies: {
        Row: MessageReply
        Insert: Omit<MessageReply, 'id' | 'created_at'> & { id?: string; created_at?: string }
        Update: Partial<MessageReply>
      }
      notifications: {
        Row: Notification
        Insert: Omit<Notification, 'id' | 'created_at'> & { id?: string; created_at?: string }
        Update: Partial<Notification>
      }
      announcements: {
        Row: Announcement
        Insert: Omit<Announcement, 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }
        Update: Partial<Announcement>
      }
      audit_log: {
        Row: AuditLog
        Insert: Omit<AuditLog, 'id' | 'created_at'> & { id?: string; created_at?: string }
        Update: Partial<AuditLog>
      }
      payment_attempts: {
        Row: PaymentAttempt
        Insert: Omit<PaymentAttempt, 'id' | 'created_at'> & { id?: string; created_at?: string }
        Update: Partial<PaymentAttempt>
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
